config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
    get 'admin/sign_up' => 'admin/registrations#new', as: 'new_madmin_registration'
    post 'admin' => 'admin/registrations#create', as: 'admin_registration'
  end

  namespace :admin do
    resources :homes, only: [:top]
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  devise_for :members, skip: :all
  devise_scope :member do
    get 'members/sign_in' => 'public/sessions#new', as: 'new_member_session'
    post 'members/sign_in' => 'public/sessions#create', as: 'member_session'
    delete 'members/sign_out' => 'public/sessions#destroy', as: 'destroy_member_session'
    get 'members/sign_up' => 'public/registrations#new', as: 'new_member_registration'
    post 'members' => 'public/registrations#create', as: 'member_registration'
  end

  scope module: :public do
    root :to => 'homes#top'
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get "search" => "searches#search"
    get 'inquiry' => 'inquiry#index'              # 入力画面
    post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
    post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
    resources :notifications, only: :index
    resources :members, only: [:show, :edit, :update, :destroy] do
      get :following, :follower, :following_index, on: :member
    end
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(member)
    favorites.where(member_id: member.id).exists?
  end
  attachment :image
  acts_as_taggable
  validates :title, :body, presence: true

  # 通知機能
  has_many :notifications, dependent: :destroy

  def create_notification_favorite!(current_member)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_member.id, member_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_member.active_notifications.new(
        post_id: id,
        visited_id: member_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_member, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:member_id).where(post_id: id).where.not(member_id: current_member.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_member, post_comment_id, temp_id['member_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_member, post_comment_id, member_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_member, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_member.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.all
  end

  def  show
    @post = Post.find(params[:id])
    @member = Member.find(@post.member.id)
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: '投稿を削除しました'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
    <div class= "row">
        <%= render 'admin/shared/post', posts: @posts %>
    </div>
</div>

app/views/admin/posts/show.html.erb
  <div class='container'>
    <div class='row'>
      <div class='col col-md-3'>
        <%= render 'admin/shared/info', member: @member %>
      </div>


      <div class='col col-md-8'>
        <div class="d-flex flex-column bd-highlight h5">
          <a>投稿日時：<%= @post.created_at.to_s(:datetime_jp) %></a>
          <a>タイトル：<%= @post.title %></a>
          <a>タグ：<%= render 'public/shared/tag_list', tag_list: @post.tag_list %></a>
        </div>

        <div class="card" style="col-8 width: 100%;">
          <a class="card-img-top"><%= attachment_image_tag @post, :image %></a>
          <div class="card-body bg-light">
            <div class="card-text h4"><%= @post.body %></div>
          </div>
        </div>


        <div class="post-info h3">
          <a><i class="fas fa-heart"></i><%= @post.favorites.count %></a><a><%=  "　　" %></a>
          <a><i class="far fa-comment-dots"></i><%= @post.post_comments.count %></a>
          <a class="d-grid justify-content-md-end">
            <%= link_to "投稿を削除する", admin_post_path(@post.id), method: :delete, class: 'btn btn-danger ', "data-confirm" => "本当に削除しますか？" %>
          </a>
        </div>
      </div>

      <div class="col col-md-8 offset-md-3">
        <% @post.post_comments.each do |post_comment| %>
          <p class="h4">
            <%= attachment_image_tag post_comment.member, :image, :fill, 40, 40 %>
            <%= post_comment.member.nickname %>
            <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
            <div class="comment-delete">
              <%= link_to "コメントを削除", admin_post_post_comment_path(post_comment.post, post_comment),class: "far fa-trash-alt btn btn-danger", method: :delete %>
            </div>
          </p>
        <% end %>
       </div>
    </div>
</div>