config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
    get 'admin/sign_up' => 'admin/registrations#new', as: 'new_madmin_registration'
    post 'admin' => 'admin/registrations#create', as: 'admin_registration'
  end

  namespace :admin do
    resources :homes, only: [:top]
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  devise_for :members, skip: :all
  devise_scope :member do
    get 'members/sign_in' => 'public/sessions#new', as: 'new_member_session'
    post 'members/sign_in' => 'public/sessions#create', as: 'member_session'
    delete 'members/sign_out' => 'public/sessions#destroy', as: 'destroy_member_session'
    get 'members/sign_up' => 'public/registrations#new', as: 'new_member_registration'
    post 'members' => 'public/registrations#create', as: 'member_registration'
  end

  scope module: :public do
    root :to => 'homes#top'
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get "search" => "searches#search"
    get 'inquiry' => 'inquiry#index'              # 入力画面
    post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
    post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
    resources :notifications, only: :index
    resources :members, only: [:show, :edit, :update, :destroy] do
      get :following, :follower, :following_index, on: :member
    end
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_info.html.erb
<div class='info'>
  <h4 class="text-center">メンバー情報</h4>
  <div class="card" style="height: 10rem;">
    <%= attachment_image_tag(member, :image, :fill, 300, 300) %>
  <ul class="list-group list-group-flush text-center">
    <li class="list-group-item bg-secondary text-white">
      <a href="<%= member_path(member) %>", class= "editlink">
        <%= member.nickname %></li>
      </a>
    <li class="list-group-item bg-secondary text-white"><今一番ハマっているゲームは？></li>
    <li class="list-group-item bg-secondary text-white"><%= member.playing_now %></li>
    <li class="list-group-item bg-secondary text-white"><自己紹介></li>
    <li class="list-group-item bg-secondary text-white"><%= member.introduction %></li>
     <li class="list-group-item">
      <a><%= member.following.count %> フォロー</a>
      <a>　</a>
      <a><%= member.follower.count %> フォロワー</a>
    </li>
  </ul>
      <div class="align-self-center width-100%">
        <%=link_to "ユーザー情報を編集する", edit_admin_member_path, class: "fas fa-edit btn btn-outline-success" %>
      </div>
  </div>
</div>

app/views/admin/shared/_members_post.html.erb
  <% posts.each do |post| %>
  <div class="d-flex p-2 bd-highlight">

    <%= link_to attachment_image_tag(post, :image, :fill, 250, 270),post_path(post) %>

   <div class="card" style="width: 100%;">
     <div class="card-header text-white">
       <%= post.member.nickname %>さんの投稿
     </div>

   <ul class="list-group list-group-flush">
      <li class="list-group-item">
        投稿日時：<%= post.created_at.to_s(:datetime_jp) %>
      </li>

      <li class="list-group-item">タイトル：<%= post.title %></li>
      <li class="list-group-item">タグ:<%= render 'public/shared/tag_list', tag_list: post.tag_list %></li>

          <li class="list-group-item">
            ♥<%= post.favorites.count %>いいね<%= "　　" %>
             <%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %>
          </li>

        <li class="list-group-item">本文：<%= post.body %></li>
      </ul>
    </div>
    </div>
  <% end %>

app/views/admin/shared/_post.html.erb
  <% posts.each do |post| %>
    <div class="d-flex p-1 bd-highlight ">
      <%= link_to attachment_image_tag(post, :image, :fill, 250, 270),admin_post_path(post) %>
      <div class="card" style="width: 100%;">
        <div class="card-header text-white">
          <%= post.member.nickname %>さんの投稿
        </div>

        <ul class="list-group list-group-flush">
          <li class="list-group-item">投稿日時：<%= post.created_at.to_s(:datetime_jp) %></li>
          <li class="list-group-item">タイトル：<%= post.title %></li>
          <li class="list-group-item">タグ:<%= render 'public/shared/tag_list', tag_list: post.tag_list %></li>
          <li class="list-group-item">♥<%= post.favorites.count %>いいね<%= "　　" %><%= "#{post.post_comments.count} コメント" %></li>
          <li class="list-group-item">本文：<%= post.body %></li>
        </ul>

      </div>
    </div>
  <% end %>