config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
    get 'admin/sign_up' => 'admin/registrations#new', as: 'new_madmin_registration'
    post 'admin' => 'admin/registrations#create', as: 'admin_registration'
  end

  namespace :admin do
    resources :homes, only: [:top]
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  devise_for :members, skip: :all
  devise_scope :member do
    get 'members/sign_in' => 'public/sessions#new', as: 'new_member_session'
    post 'members/sign_in' => 'public/sessions#create', as: 'member_session'
    delete 'members/sign_out' => 'public/sessions#destroy', as: 'destroy_member_session'
    get 'members/sign_up' => 'public/registrations#new', as: 'new_member_registration'
    post 'members' => 'public/registrations#create', as: 'member_registration'
  end

  scope module: :public do
    root :to => 'homes#top'
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get "search" => "searches#search"
    get 'inquiry' => 'inquiry#index'              # 入力画面
    post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
    post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
    resources :notifications, only: :index
    resources :members, only: [:show, :edit, :update, :destroy] do
      get :following, :follower, :following_index, on: :member
    end
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/_footer.html.erb
<footer class="footer h4 text-center" id="footer" style="height: 80px; line-height: 80px;">©︎ 2021 game snap</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm" id="header">
    <nav class="navbar navbar-expand-lg navbar-white">
      <div class="container">
        <a class="navbar-brand" href="/"><%= image_tag('logo.jpg', class: 'logo-image') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown" >
          <ul class="navbar-nav ml-auto">
            <% if member_signed_in? %>
              <li class=nav-list ><i class="far fa-file btn btn-light "><%= link_to ' 新規投稿', new_post_path, class: 'text-dark' %></i></li>
              <li class=nav-list style="margin-left: 10px;" ><i class="far fa-newspaper btn btn-light"><%= link_to ' 投稿一覧', posts_path, class: 'text-dark' %></i></li>
              <li class=nav-list style="margin-left: 10px;" ><i class="fab fa-connectdevelop btn btn-light"><%= link_to ' タイムライン', following_index_member_path(current_member), class: "text-dark" %></i></li>
              <li class=nav-list style="margin-left: 10px;" ><i class="fas fa-user btn btn-light"><%= link_to ' マイページ', member_path(current_member), class: "text-dark" %></i></li>
              <li class=nav-list style="margin-left: 10px;" >
                <% if unchecked_notifications.any? %>
                  <span class="fa-stack" id="n-circle"><i class="fas fa-circle n-circle fa-stack-1x"></i></span>
                <% end %>
                <i class="far fa-bell btn btn-light "><%= link_to ' 通知', notifications_path(current_member), class: "text-dark" %></i></li>
              <li class=nav-list style="margin-left: 10px;" ><%= link_to ' ログアウト', destroy_member_session_path, method: :delete, class: "btn btn-light text-dark" %></li>
              <li class="nav-item nav-link text-dark">ようこそ<%= current_member.nickname %><small>さん</small><i class="far fa-grin-wink"></i></li>
            <% elsif admin_signed_in? %>
              <li class=nav-list><%= link_to ' メンバー一覧', admin_members_path, class: 'btn btn-outline-secondary text-white' %></li>
              <li class=nav-list style="margin-left: 10px;" ><%= link_to ' 投稿一覧', admin_posts_path, class: "btn btn-outline-secondary text-white" %></li>
              <li class=nav-list style="margin-left: 10px;" ><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete,class: "btn btn-outline-secondary text-white" %></li>
              <li class="nav-item nav-link text-light">管理者ログイン中：<%= current_admin.email %><small>さん</small></li>
            <% else %>
              <li class=nav-list><%= link_to ' 新規登録', new_member_registration_path, class: "btn btn-light text-dark" %></li>
              <li class=nav-list style="margin-left: 10px;" ><%= link_to ' ログイン', new_member_session_path, class: "btn btn-light text-dark" %></li>
              <li class=nav-list style="margin-left: 10px;" ><%= link_to ' ゲストログイン（閲覧用）', homes_guest_sign_in_path, class: "btn btn-light text-dark", method: :post %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <meta charset="utf-8">
    <!--レスポンシブ-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GameSnap</title>
    <link rel="stylesheet" href="app/assets/stylesheets/reset.scss" >
    <!-- BootstrapのCSS読み込み -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<script type="text/javascript" src="./footerFixed.js"></script>-->
  </head>
  <body class="body">
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <% if flash[:notice] %>
        <div class="flash h2 col-12 bg-white text-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <div id="contents">
      <%= yield %>
      </div>

      <%= render 'layouts/footer' %>
    </div>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>